"""edit portfolio

Revision ID: c882fbf05ed3
Revises: dc09b1bdb613
Create Date: 2025-06-02 14:34:53.043353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
from sqlalchemy.dialects.postgresql import ARRAY, JSONB

# revision identifiers, used by Alembic.
revision: str = 'c882fbf05ed3'
down_revision: Union[str, None] = 'dc09b1bdb613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('introduce', sa.VARCHAR(), nullable=True))
    op.add_column('portfolio', sa.Column('job', sa.VARCHAR(), nullable=True))
    op.add_column('portfolio', sa.Column('techs', ARRAY(sa.VARCHAR), nullable=True))
    op.add_column('portfolio', sa.Column('careers', ARRAY(JSONB), nullable=True))
    op.add_column('portfolio', sa.Column('projects', ARRAY(JSONB), nullable=True))
    op.add_column('portfolio', sa.Column('educations', ARRAY(JSONB), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'educations')
    op.drop_column('portfolio', 'projects')
    op.drop_column('portfolio', 'careers')
    op.drop_column('portfolio', 'techs')
    op.drop_column('portfolio', 'job')
    op.drop_column('portfolio', 'introduce')
    # ### end Alembic commands ###
