"""create chat

Revision ID: fb771009b3e4
Revises: 9ba332328e8c
Create Date: 2025-04-26 22:11:11.926702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fb771009b3e4'
down_revision: Union[str, None] = '9ba332328e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'last_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
